package net.skyrimcraft;

import java.util.Arrays;

import net.skyrimcraft.packet.SkyrimcraftPacketHandler;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.network.NetworkMod;

@Mod(modid=Skyrimcraft.modID, version="1.6.2", name="Skyrimcraft")
@NetworkMod(clientSideRequired = true, serverSideRequired = false, channels={"skyrimcraft"}, packetHandler = SkyrimcraftPacketHandler.class)
public class Skyrimcraft
{
	public static final String modID = "skyrimcraft";
	
	@EventHandler
	public void preInit(FMLPreInitializationEvent event) {
		ModMetadata data = event.getModMetadata();
		data.autogenerated = false;
		data.modId = modID;
		data.name = "Skyrimcraft";
		data.logoFile = "";
		data.version = "1.0.0";
		data.url = "No website available...";
		data.authorList = Arrays.asList(new String[] { "Madcrazydrumma", "Sheenrox82" });
		data.description = "This mod will ultimately bring as much of the Skyrim world to Minecraft as possible. It will eventually contain an RPG realm; where players can play one of the most exciting games in another amazing game, Minecraft! While it's state may not include everything you are looking for, we can assure you that Skyrimcraft will overhaul your gaming experience bringing the realistic Skyrim world to life inside a 3D blocky landscape. We hope you enjoy this mod just as much as we enjoyed making it!";
	}
}